#include "led.h"

void LED_GPIO_Config(void)
{
	GPIO_InitTypeDef GPIO_InitStruct;

	LED1_GPIO_CLK_ENABLE();
	LED2_GPIO_CLK_ENABLE();
	LED3_GPIO_CLK_ENABLE();
	LED4_GPIO_CLK_ENABLE();

	//LED1_GPIO_CLK_DISABLE();
	//LED2_GPIO_CLK_DISABLE();
	//LED3_GPIO_CLK_DISABLE();
	//LED4_GPIO_CLK_DISABLE();


	GPIO_InitStruct.Pin = LED1_PIN;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Pull = GPIO_PULLUP;
	GPIO_InitStruct.Speed = GPIO_SPEED_HIGH;
	HAL_GPIO_Init(LED1_GPIO_PORT, &GPIO_InitStruct);

	GPIO_InitStruct.Pin = LED2_PIN;
	HAL_GPIO_Init(LED2_GPIO_PORT, &GPIO_InitStruct);

	GPIO_InitStruct.Pin = LED3_PIN;
	HAL_GPIO_Init(LED3_GPIO_PORT, &GPIO_InitStruct);

	GPIO_InitStruct.Pin = LED4_PIN;
	HAL_GPIO_Init(LED4_GPIO_PORT, &GPIO_InitStruct);

	//LED1_GPIO_CLK_DISABLE();
	//LED2_GPIO_CLK_DISABLE();
	//LED3_GPIO_CLK_DISABLE();
	//LED4_GPIO_CLK_DISABLE();


	LED_RGYOFF;

	
}

void LED_GPIO_DeConfig(void)
{
	LED1_GPIO_CLK_DISABLE();
	LED2_GPIO_CLK_DISABLE();
	LED3_GPIO_CLK_DISABLE();
	LED4_GPIO_CLK_DISABLE();

	//HAL_GPIO_DeInit(LED1_GPIO_PORT, LED1_PIN);
	//HAL_GPIO_DeInit(LED2_GPIO_PORT, LED2_PIN);
	//HAL_GPIO_DeInit(LED3_GPIO_PORT, LED3_PIN);
	//HAL_GPIO_DeInit(LED4_GPIO_PORT, LED4_PIN);
}

void USART3_GPIO_Config(void)
{
		GPIO_InitTypeDef GPIO_InitStruct;
		__GPIOC_CLK_ENABLE();
	
	GPIO_InitStruct.Pin = GPIO_PIN_10;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Pull = GPIO_PULLUP;
	GPIO_InitStruct.Speed = GPIO_SPEED_HIGH;
	HAL_GPIO_Init(GPIOC, &GPIO_InitStruct);		
}
